{{--{!! Form::select($name1,['臺北市'=>'臺北市','新北市'=>'新北市'], null, ['placeholder' => '請選擇縣市','id'=>'add1']) !!}--}}
{!! Form::select($name1, ['基隆市'=>'基隆市',
	'臺北市'=>'臺北市',
	'新北市'=>'新北市',
	'桃園市'=>'桃園市',
	'新竹市'=>'新竹市',
	'新竹縣'=>'新竹縣',
	'苗栗縣'=>'苗栗縣',
	'臺中市'=>'臺中市',
	'彰化縣'=>'彰化縣',
	'南投縣'=>'南投縣',
	'雲林縣'=>'雲林縣',
	'嘉義市'=>'嘉義市',
	'嘉義縣'=>'嘉義縣',
	'臺南市'=>'臺南市',
	'高雄市'=>'高雄市',
	'屏東縣'=>'屏東縣',
	'臺東縣'=>'臺東縣',
	'花蓮縣'=>'花蓮縣',
	'宜蘭縣'=>'宜蘭縣',
	'澎湖縣'=>'澎湖縣',
	'金門縣'=>'金門縣',
	'連江縣'=>'連江縣'
], null, ['placeholder' => '請選擇縣市','id'=>$name1])!!}
<select name={{$name2}} id={{$name2}}>
    <option value="仁愛區" class="基隆市">仁愛區</option>
    <option value="信義區" class="基隆市">信義區</option>
    <option value="中正區" class="基隆市">中正區</option>
    <option value="中山區" class="基隆市">中山區</option>
    <option value="安樂區" class="基隆市">安樂區</option>
    <option value="暖暖區" class="基隆市">暖暖區</option>
    <option value="七堵區" class="基隆市">七堵區</option>
    <option value="中正區" class="臺北市">中正區</option>
    <option value="大同區" class="臺北市">大同區</option>
    <option value="中山區" class="臺北市">中山區</option>
    <option value="松山區" class="臺北市">松山區</option>
    <option value="大安區" class="臺北市">大安區</option>
    <option value="萬華區" class="臺北市">萬華區</option>
    <option value="信義區" class="臺北市">信義區</option>
    <option value="士林區" class="臺北市">士林區</option>
    <option value="北投區" class="臺北市">北投區</option>
    <option value="內湖區" class="臺北市">內湖區</option>
    <option value="南港區" class="臺北市">南港區</option>
    <option value="文山區" class="臺北市">文山區</option>
    <option value="萬里區" class="新北市">萬里區</option>
    <option value="金山區" class="新北市">金山區</option>
    <option value="板橋區" class="新北市">板橋區</option>
    <option value="汐止區" class="新北市">汐止區</option>
    <option value="深坑區" class="新北市">深坑區</option>
    <option value="石碇區" class="新北市">石碇區</option>
    <option value="瑞芳區" class="新北市">瑞芳區</option>
    <option value="平溪區" class="新北市">平溪區</option>
    <option value="雙溪區" class="新北市">雙溪區</option>
    <option value="貢寮區" class="新北市">貢寮區</option>
    <option value="新店區" class="新北市">新店區</option>
    <option value="坪林區" class="新北市">坪林區</option>
    <option value="烏來區" class="新北市">烏來區</option>
    <option value="永和區" class="新北市">永和區</option>
    <option value="中和區" class="新北市">中和區</option>
    <option value="土城區" class="新北市">土城區</option>
    <option value="三峽區" class="新北市">三峽區</option>
    <option value="樹林區" class="新北市">樹林區</option>
    <option value="鶯歌區" class="新北市">鶯歌區</option>
    <option value="三重區" class="新北市">三重區</option>
    <option value="新莊區" class="新北市">新莊區</option>
    <option value="泰山區" class="新北市">泰山區</option>
    <option value="林口區" class="新北市">林口區</option>
    <option value="蘆洲區" class="新北市">蘆洲區</option>
    <option value="五股區" class="新北市">五股區</option>
    <option value="八里區" class="新北市">八里區</option>
    <option value="淡水區" class="新北市">淡水區</option>
    <option value="三芝區" class="新北市">三芝區</option>
    <option value="石門區" class="新北市">石門區</option>
    <option value="中壢區" class="桃園市">中壢區</option>
    <option value="平鎮區" class="桃園市">平鎮區</option>
    <option value="龍潭區" class="桃園市">龍潭區</option>
    <option value="楊梅區" class="桃園市">楊梅區</option>
    <option value="新屋區" class="桃園市">新屋區</option>
    <option value="觀音區" class="桃園市">觀音區</option>
    <option value="桃園區" class="桃園市">桃園區</option>
    <option value="龜山區" class="桃園市">龜山區</option>
    <option value="八德區" class="桃園市">八德區</option>
    <option value="大溪區" class="桃園市">大溪區</option>
    <option value="復興區" class="桃園市">復興區</option>
    <option value="大園區" class="桃園市">大園區</option>
    <option value="蘆竹區" class="桃園市">蘆竹區</option>
    <option value="東區" class="新竹市">東區</option>
    <option value="北區" class="新竹市">北區</option>
    <option value="香山區" class="新竹市">香山區</option>
    <option value="竹北市" class="新竹縣">竹北市</option>
    <option value="湖口鄉" class="新竹縣">湖口鄉</option>
    <option value="新豐鄉" class="新竹縣">新豐鄉</option>
    <option value="新埔鎮" class="新竹縣">新埔鎮</option>
    <option value="關西鎮" class="新竹縣">關西鎮</option>
    <option value="芎林鄉" class="新竹縣">芎林鄉</option>
    <option value="寶山鄉" class="新竹縣">寶山鄉</option>
    <option value="竹東鎮" class="新竹縣">竹東鎮</option>
    <option value="五峰鄉" class="新竹縣">五峰鄉</option>
    <option value="橫山鄉" class="新竹縣">橫山鄉</option>
    <option value="尖石鄉" class="新竹縣">尖石鄉</option>
    <option value="北埔鄉" class="新竹縣">北埔鄉</option>
    <option value="峨嵋鄉" class="新竹縣">峨眉鄉</option>
    <option value="竹南鎮" class="苗栗縣">竹南鎮</option>
    <option value="頭份鎮" class="苗栗縣">頭份鎮</option>
    <option value="三灣鄉" class="苗栗縣">三灣鄉</option>
    <option value="南庄鄉" class="苗栗縣">南庄鄉</option>
    <option value="獅潭鄉" class="苗栗縣">獅潭鄉</option>
    <option value="後龍鎮" class="苗栗縣">後龍鎮</option>
    <option value="通霄鎮" class="苗栗縣">通霄鎮</option>
    <option value="苑裡鎮" class="苗栗縣">苑裡鎮</option>
    <option value="苗栗市" class="苗栗縣">苗栗市</option>
    <option value="造橋鄉" class="苗栗縣">造橋鄉</option>
    <option value="頭屋鄉" class="苗栗縣">頭屋鄉</option>
    <option value="公館鄉" class="苗栗縣">公館鄉</option>
    <option value="大湖鄉" class="苗栗縣">大湖鄉</option>
    <option value="泰安鄉" class="苗栗縣">泰安鄉</option>
    <option value="銅鑼鄉" class="苗栗縣">銅鑼鄉</option>
    <option value="三義鄉" class="苗栗縣">三義鄉</option>
    <option value="西湖鄉" class="苗栗縣">西湖鄉</option>
    <option value="卓蘭鎮" class="苗栗縣">卓蘭鎮</option>
    <option value="中區" class="臺中市">中區</option>
    <option value="東區" class="臺中市">東區</option>
    <option value="南區" class="臺中市">南區</option>
    <option value="西區" class="臺中市">西區</option>
    <option value="北區" class="臺中市">北區</option>
    <option value="北屯區" class="臺中市">北屯區</option>
    <option value="西屯區" class="臺中市">西屯區</option>
    <option value="南屯區" class="臺中市">南屯區</option>
    <option value="太平區" class="臺中市">太平區</option>
    <option value="大里區" class="臺中市">大里區</option>
    <option value="霧峰區" class="臺中市">霧峰區</option>
    <option value="烏日區" class="臺中市">烏日區</option>
    <option value="豐原區" class="臺中市">豐原區</option>
    <option value="后里區" class="臺中市">后里區</option>
    <option value="石岡區" class="臺中市">石岡區</option>
    <option value="東勢區" class="臺中市">東勢區</option>
    <option value="和平區" class="臺中市">和平區</option>
    <option value="新社區" class="臺中市">新社區</option>
    <option value="潭子區" class="臺中市">潭子區</option>
    <option value="大雅區" class="臺中市">大雅區</option>
    <option value="神岡區" class="臺中市">神岡區</option>
    <option value="大肚區" class="臺中市">大肚區</option>
    <option value="沙鹿區" class="臺中市">沙鹿區</option>
    <option value="龍井區" class="臺中市">龍井區</option>
    <option value="梧棲區" class="臺中市">梧棲區</option>
    <option value="清水區" class="臺中市">清水區</option>
    <option value="大甲區" class="臺中市">大甲區</option>
    <option value="外埔區" class="臺中市">外埔區</option>
    <option value="大安區" class="臺中市">大安區</option>
    <option value="彰化市" class="彰化縣">彰化市</option>
    <option value="芬園鄉" class="彰化縣">芬園鄉</option>
    <option value="花壇鄉" class="彰化縣">芬園鄉</option>
    <option value="秀水鄉" class="彰化縣">秀水鄉</option>
    <option value="鹿港鎮" class="彰化縣">鹿港鎮</option>
    <option value="福興鄉" class="彰化縣">福興鄉</option>
    <option value="線西鄉" class="彰化縣">線西鄉</option>
    <option value="和美鎮" class="彰化縣">和美鎮</option>
    <option value="伸港鄉" class="彰化縣">伸港鄉</option>
    <option value="員林鎮" class="彰化縣">員林鎮</option>
    <option value="社頭鄉" class="彰化縣">社頭鄉</option>
    <option value="永靖鄉" class="彰化縣">永靖鄉</option>
    <option value="埔心鄉" class="彰化縣">埔心鄉</option>
    <option value="溪湖鎮" class="彰化縣">溪湖鎮</option>
    <option value="大村鄉" class="彰化縣">大村鄉</option>
    <option value="埔鹽鄉" class="彰化縣">埔鹽鄉</option>
    <option value="田中鎮" class="彰化縣">田中鎮</option>
    <option value="北斗鎮" class="彰化縣">北斗鎮</option>
    <option value="田尾鄉" class="彰化縣">田尾鄉</option>
    <option value="埤頭鄉" class="彰化縣">埤頭鄉</option>
    <option value="溪州鄉" class="彰化縣">溪州鄉</option>
    <option value="竹塘鄉" class="彰化縣">竹塘鄉</option>
    <option value="二林鎮" class="彰化縣">二林鎮</option>
    <option value="大城鄉" class="彰化縣">大城鄉</option>
    <option value="芳苑鄉" class="彰化縣">芳苑鄉</option>
    <option value="二水鄉" class="彰化縣">二水鄉</option>
    <option value="南投市" class="南投縣">南投市</option>
    <option value="中寮鄉" class="南投縣">中寮鄉</option>
    <option value="草屯鎮" class="南投縣">草屯鎮</option>
    <option value="國姓鄉" class="南投縣">國姓鄉</option>
    <option value="埔里鄉" class="南投縣">埔里鄉</option>
    <option value="仁愛鎮" class="南投縣">仁愛鎮</option>
    <option value="名間鎮" class="南投縣">名間鎮</option>
    <option value="集集鎮" class="南投縣">集集鎮</option>
    <option value="水里鄉" class="南投縣">水里鄉</option>
    <option value="魚池鄉" class="南投縣">魚池鄉</option>
    <option value="信義鄉" class="南投縣">信義鄉</option>
    <option value="竹山鎮" class="南投縣">竹山鎮</option>
    <option value="鹿谷鄉" class="南投縣">鹿谷鄉</option>
    <option value="斗南鎮" class="雲林縣">斗南鎮</option>
    <option value="大埤鄉" class="雲林縣">大埤鄉</option>
    <option value="虎尾鎮" class="雲林縣">虎尾鎮</option>
    <option value="土庫鎮" class="雲林縣">土庫鎮</option>
    <option value="褒忠鄉" class="雲林縣">褒忠鄉</option>
    <option value="東勢鄉" class="雲林縣">東勢鄉</option>
    <option value="臺西鄉" class="雲林縣">臺西鄉</option>
    <option value="崑崙鄉" class="雲林縣">崑崙鄉</option>
    <option value="麥寮鄉" class="雲林縣">麥寮鄉</option>
    <option value="斗六市" class="雲林縣">斗六市</option>
    <option value="林內鄉" class="雲林縣">林內鄉</option>
    <option value="古坑鄉" class="雲林縣">古坑鄉</option>
    <option value="莿桐鄉" class="雲林縣">莿桐鄉</option>
    <option value="西螺鄉" class="雲林縣">西螺鄉</option>
    <option value="二崙鄉" class="雲林縣">二崙鄉</option>
    <option value="北港鎮" class="雲林縣">北港鎮</option>
    <option value="水林鄉" class="雲林縣">斗南鄉</option>
    <option value="口湖鄉" class="雲林縣">斗南鄉</option>
    <option value="四湖鄉" class="雲林縣">四湖鄉</option>
    <option value="元長鄉" class="雲林縣">元長鄉</option>
    <option value="東區" class="嘉義市">東區</option>
    <option value="西區" class="嘉義市">西區</option>
    <option value="番路鄉" class="嘉義縣">番路鄉</option>
    <option value="梅山鄉" class="嘉義縣">梅山鄉</option>
    <option value="竹崎鄉" class="嘉義縣">竹崎鄉</option>
    <option value="阿里山" class="嘉義縣">阿里山</option>
    <option value="中埔鄉" class="嘉義縣">中埔鄉</option>
    <option value="大埔鄉" class="嘉義縣">大埔鄉</option>
    <option value="水上鄉" class="嘉義縣">水上鄉</option>
    <option value="鹿草鄉" class="嘉義縣">鹿草鄉</option>
    <option value="太保市" class="嘉義縣">太保市</option>
    <option value="朴子市" class="嘉義縣">朴子市</option>
    <option value="東石鄉" class="嘉義縣">東石鄉</option>
    <option value="六腳鄉" class="嘉義縣">六腳鄉</option>
    <option value="新港鄉" class="嘉義縣">新港鄉</option>
    <option value="民雄鄉" class="嘉義縣">民雄鄉</option>
    <option value="大林鎮" class="嘉義縣">大林鄉</option>
    <option value="溪口鄉" class="嘉義縣">溪口鄉</option>
    <option value="義竹鄉" class="嘉義縣">義竹鄉</option>
    <option value="布袋鎮" class="嘉義縣">布袋鎮</option>
    <option value="中西區" class="臺南市">中西區</option>
    <option value="東區" class="臺南市">東區</option>
    <option value="南區" class="臺南市">南區</option>
    <option value="北區" class="臺南市">北區</option>
    <option value="安平區" class="臺南市">安平區</option>
    <option value="安南區" class="臺南市">安南區</option>
    <option value="永康區" class="臺南市">永康區</option>
    <option value="歸仁區" class="臺南市">歸仁區</option>
    <option value="新化區" class="臺南市">新化區</option>
    <option value="左鎮區" class="臺南市">左鎮區</option>
    <option value="玉井區" class="臺南市">玉井區</option>
    <option value="楠西區" class="臺南市">楠西區</option>
    <option value="南化區" class="臺南市">南化區</option>
    <option value="仁德區" class="臺南市">仁德區</option>
    <option value="關廟區" class="臺南市">關廟區</option>
    <option value="龍崎區" class="臺南市">龍崎區</option>
    <option value="官田區" class="臺南市">官田區</option>
    <option value="麻豆區" class="臺南市">麻豆區</option>
    <option value="佳里區" class="臺南市">佳里區</option>
    <option value="西港區" class="臺南市">西港區</option>
    <option value="七股區" class="臺南市">七股區</option>
    <option value="將軍區" class="臺南市">將軍區</option>
    <option value="學甲區" class="臺南市">學甲區</option>
    <option value="北門區" class="臺南市">北門區</option>
    <option value="新營區" class="臺南市">新營區</option>
    <option value="後壁區" class="臺南市">後壁區</option>
    <option value="白河區" class="臺南市">白河區</option>
    <option value="東山區" class="臺南市">東山區</option>
    <option value="六甲區" class="臺南市">六甲區</option>
    <option value="下營區" class="臺南市">下營區</option>
    <option value="柳營區" class="臺南市">柳營區</option>
    <option value="鹽水區" class="臺南市">鹽水區</option>
    <option value="善化區" class="臺南市">善化區</option>
    <option value="大內區" class="臺南市">大內區</option>
    <option value="山上區" class="臺南市">山上區</option>
    <option value="新市區" class="臺南市">新市區</option>
    <option value="安定區" class="臺南市">安定區</option>
    <option value="新興區" class="高雄市">新興區</option>
    <option value="前金區" class="高雄市">前金區</option>
    <option value="苓雅區" class="高雄市">苓雅區</option>
    <option value="鹽埕區" class="高雄市">鹽埕區</option>
    <option value="鼓山區" class="高雄市">鼓山區</option>
    <option value="旗津區" class="高雄市">旗津區</option>
    <option value="前鎮區" class="高雄市">前鎮區</option>
    <option value="三民區" class="高雄市">三民區</option>
    <option value="楠梓區" class="高雄市">楠梓區</option>
    <option value="小港區" class="高雄市">小港區</option>
    <option value="左營區" class="高雄市">左營區</option>
    <option value="仁武區" class="高雄市">仁武區</option>
    <option value="大社區" class="高雄市">大社區</option>
    <option value="岡山區" class="高雄市">岡山區</option>
    <option value="路竹區" class="高雄市">路竹區</option>
    <option value="阿蓮區" class="高雄市">阿蓮區</option>
    <option value="田寮區" class="高雄市">田寮區</option>
    <option value="燕巢區" class="高雄市">燕巢區</option>
    <option value="橋頭區" class="高雄市">橋頭區</option>
    <option value="梓官區" class="高雄市">梓官區</option>
    <option value="彌陀區" class="高雄市">彌陀區</option>
    <option value="永安區" class="高雄市">永安區</option>
    <option value="湖內區" class="高雄市">湖內區</option>
    <option value="鳳山區" class="高雄市">夢山區</option>
    <option value="大寮區" class="高雄市">大寮區</option>
    <option value="林園區" class="高雄市">林園區</option>
    <option value="鳥松區" class="高雄市">鳥松區</option>
    <option value="大樹區" class="高雄市">大樹區</option>
    <option value="旗山區" class="高雄市">旗山區</option>
    <option value="美濃區" class="高雄市">美濃區</option>
    <option value="六龜區" class="高雄市">六龜區</option>
    <option value="內門區" class="高雄市">內門區</option>
    <option value="杉林區" class="高雄市">杉林區</option>
    <option value="甲仙區" class="高雄市">甲仙區</option>
    <option value="桃源區" class="高雄市">桃源區</option>
    <option value="那瑪夏" class="高雄市">那瑪夏</option>
    <option value="茂林區" class="高雄市">茂林區</option>
    <option value="茄萣區" class="高雄市">茄萣區</option>
    <option value="屏東市" class="屏東縣">屏東市</option>
    <option value="三地門" class="屏東縣">三地門</option>
    <option value="霧臺鄉" class="屏東縣">霧臺鄉</option>
    <option value="瑪家鄉" class="屏東縣">萬里鄉</option>
    <option value="九如鄉" class="屏東縣">九如鄉</option>
    <option value="里港鄉" class="屏東縣">里港鄉</option>
    <option value="高樹鄉" class="屏東縣">高樹鄉</option>
    <option value="鹽埔鄉" class="屏東縣">鹽埔鄉</option>
    <option value="長治鄉" class="屏東縣">長治鄉</option>
    <option value="麟洛鄉" class="屏東縣">麟洛鄉</option>
    <option value="竹田鄉" class="屏東縣">竹田鄉</option>
    <option value="內埔鄉" class="屏東縣">內埔鄉</option>
    <option value="萬丹鄉" class="屏東縣">萬丹鄉</option>
    <option value="潮州鎮" class="屏東縣">潮洲鎮</option>
    <option value="泰武鄉" class="屏東縣">泰武鄉</option>
    <option value="來義鄉" class="屏東縣">來義鄉</option>
    <option value="萬巒鄉" class="屏東縣">萬巒鄉</option>
    <option value="崁頂鄉" class="屏東縣">崁頂鄉</option>
    <option value="新埤鄉" class="屏東縣">新埤鄉</option>
    <option value="南州鄉" class="屏東縣">南州鄉</option>
    <option value="林邊鄉" class="屏東縣">林邊鄉</option>
    <option value="東港鎮" class="屏東縣">東港鎮</option>
    <option value="琉球鄉" class="屏東縣">琉球鄉</option>
    <option value="佳冬鄉" class="屏東縣">佳冬鄉</option>
    <option value="新園鄉" class="屏東縣">新園鄉</option>
    <option value="枋寮鄉" class="屏東縣">枋寮鄉</option>
    <option value="枋山鄉" class="屏東縣">枋山鄉</option>
    <option value="春日鄉" class="屏東縣">春日鄉</option>
    <option value="獅子鄉" class="屏東縣">獅子鄉</option>
    <option value="車城鄉" class="屏東縣">車城鄉</option>
    <option value="牡丹鄉" class="屏東縣">牡丹鄉</option>
    <option value="恆春鎮" class="屏東縣">恆春鎮</option>
    <option value="滿洲鄉" class="屏東縣">滿洲鄉</option>
    <option value="臺東市" class="臺東縣">臺東市</option>
    <option value="綠島鄉" class="臺東縣">綠島鄉</option>
    <option value="蘭嶼鄉" class="臺東縣">蘭嶼鄉</option>
    <option value="延平鄉" class="臺東縣">延平鄉</option>
    <option value="卑南鄉" class="臺東縣">卑南鄉</option>
    <option value="鹿野鄉" class="臺東縣">鹿野鄉</option>
    <option value="關山鎮" class="臺東縣">關山鎮</option>
    <option value="海瑞鄉" class="臺東縣">海瑞鄉</option>
    <option value="池上鄉" class="臺東縣">池上鄉</option>
    <option value="東河鄉" class="臺東縣">東河鄉</option>
    <option value="成功鎮" class="臺東縣">成功鎮</option>
    <option value="長濱鄉" class="臺東縣">長濱鄉</option>
    <option value="太麻里" class="臺東縣">太麻里</option>
    <option value="金峰鄉" class="臺東縣">金峰鄉</option>
    <option value="大武鄉" class="臺東縣">大武鄉</option>
    <option value="達仁鄉" class="臺東縣">達仁鄉</option>
    <option value="花蓮市" class="花蓮縣">花蓮市</option>
    <option value="新城鄉" class="花蓮縣">新城鄉</option>
    <option value="秀林鄉" class="花蓮縣">秀林鄉</option>
    <option value="吉安鄉" class="花蓮縣">吉安鄉</option>
    <option value="壽豐鄉" class="花蓮縣">豐壽鄉</option>
    <option value="鳳林鎮" class="花蓮縣">鳳林鎮</option>
    <option value="光復鄉" class="花蓮縣">光復鄉</option>
    <option value="豐濱鄉" class="花蓮縣">豐濱鄉</option>
    <option value="瑞穗鄉" class="花蓮縣">瑞穗鄉</option>
    <option value="萬榮鄉" class="花蓮縣">萬榮鄉</option>
    <option value="玉里鎮" class="花蓮縣">玉里鎮</option>
    <option value="卓溪鄉" class="花蓮縣">卓溪鄉</option>
    <option value="富里鄉" class="花蓮縣">富里鄉</option>
    <option value="宜蘭市" class="宜蘭縣">宜蘭市</option>
    <option value="頭城鎮" class="宜蘭縣">頭城鎮</option>
    <option value="礁溪鄉" class="宜蘭縣">礁溪鄉</option>
    <option value="壯圍鄉" class="宜蘭縣">壯圍鄉</option>
    <option value="員山鄉" class="宜蘭縣">員山鄉</option>
    <option value="羅東鎮" class="宜蘭縣">羅東鎮</option>
    <option value="三星鄉" class="宜蘭縣">三星鄉</option>
    <option value="大同鄉" class="宜蘭縣">大同鄉</option>
    <option value="五結鄉" class="宜蘭縣">五結鄉</option>
    <option value="冬山鄉" class="宜蘭縣">冬山鄉</option>
    <option value="蘇澳鎮" class="宜蘭縣">蘇澳鎮</option>
    <option value="南澳鄉" class="宜蘭縣">南澳鄉</option>
    <option value="馬公市" class="澎湖縣">馬公市</option>
    <option value="西嶼鄉" class="澎湖縣">西嶼鄉</option>
    <option value="望安鄉" class="澎湖縣">望安鄉</option>
    <option value="七美鄉" class="澎湖縣">七美鄉</option>
    <option value="白沙鄉" class="澎湖縣">白沙鄉</option>
    <option value="湖西鄉" class="澎湖縣">湖西鄉</option>
    <option value="金沙鎮" class="金門縣">金沙鎮</option>
    <option value="金湖鎮" class="金門縣">金湖鎮</option>
    <option value="金寧鄉" class="金門縣">金寧鄉</option>
    <option value="金城鎮" class="金門縣">金城鎮</option>
    <option value="烈嶼鄉" class="金門縣">烈嶼鄉</option>
    <option value="烏坵鄉" class="金門縣">烏坵鄉</option>
    <option value="南竿鄉" class="連江縣">南竿鄉</option>
    <option value="北竿鄉" class="連江縣">北竿鄉</option>
    <option value="莒光鄉" class="連江縣">莒光鄉</option>
    <option value="東引鄉" class="連江縣">東引鄉</option>
</select>

<script>$("#{{$name2}}").chained("#{{$name1}}");</script>


